### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by miso-xyz**
dawg just be honest lmao

### CODE REVIEW

**Comment by 0x11DFE** [comment]
This goes for you as well.
I have no idea if this is sarcastic or you are being serious.

**Comment by miso-xyz** [comment]
> This goes for you as well.
> I have no idea if this is sarcastic or you are being serious.

both, i used to be an avid cracker, but what youve uploaded is clearly a tool to crack NetLimiter, saying you dont support cracking and that this is for educational purposes only is ridiculous

**Comment by 0x11DFE** [comment]
It might be "ridiculous" for you but i am actually not supporting it.
To prevent such patch it only requires to pack/protect the application.

**Comment by miso-xyz** [comment]
consider telling the devs if you havent, people will most likely use it to illegally egister NetLimiter

**Comment by CursedLand** [comment]
l

**Comment by CursedLand** [comment]
m

**Comment by CursedLand** [comment]
a

**Comment by CursedLand** [comment]
o

**Pull request closed without merging**
